### ISSUE TITLE
Jobs link is wrong

### ISSUE THREAD

**Issue by john-light** [aragonone/website#3]
When I open then close one of the job listings, the URL bar shows https://aragon.one/#job but the actual URL for the job section should be https://aragon.one/#jobs

**Comment by Git-R-Goin** [comment]
Hi @luisivan From the Angelist, I noticed that you are looking for frontend developer experienced in React. I am very interested in your position and would like to apply with my FrontEnd skill.
My email address is newbeestar@outlook.com Thanks

**Comment by luisivan** [comment]
Hey @Git-R-Goin you can check out how to apply at https://aragon.one/#frontend-engineer

**Comment by luisivan** [comment]
@delfipolito this seems to be an issue, can you plz fix it? Thanks!
